"""empty message

Revision ID: 615b85b71e51
Revises: 
Create Date: 2022-09-08 07:22:31.931682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615b85b71e51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam')
    # ### end Alembic commands ###
