"""empty message

Revision ID: 91c9ef4dfcf6
Revises: e6c617c934f3
Create Date: 2022-09-08 07:27:55.522518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91c9ef4dfcf6'
down_revision = 'e6c617c934f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('email', mysql.VARCHAR(length=200), nullable=False))
    # ### end Alembic commands ###
