"""empty message

Revision ID: e6c617c934f3
Revises: 615b85b71e51
Create Date: 2022-09-08 07:23:41.661170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c617c934f3'
down_revision = '615b85b71e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('email', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'email')
    # ### end Alembic commands ###
